variables:

  # app version, changing version will auto deploy the app to current version
  devBuildImageVersion: "2.1.10"

  # always add prefix k- before production image version
  prodBuildImageVersion: "prod-2.1.12"

  #app buil image
  imageRepository: "registry.nise.gov.bd/nise3-cms-api-service"
