variables:

  # app version, changing version will auto deploy the app to current version
  devBuildImageVersion: "2.1.16"

  # always add prefix k- before production image version
  prodBuildImageVersion: "prod-2.1.14"

  #app build image
  imageRepository: "registry.nise.gov.bd/nise3-cms-api-service"
